//
//  CefVersion.h
//  CefViewCore
//
//  Created by Sheen Tian on 2025/1/19.
//  This file was generated during CMake configuring.
//  Do not edit this file directly by manual.
//  Edit the CefVersion.h.in and then re-config project with CMake.
//

#ifndef CefVersion_h
#define CefVersion_h
#pragma once

// clang-format off
#define CEF_VERSION "137.0.10+g7e14fe1+chromium-137.0.7151.69"
#define CEF_VERSION_MAJOR 137
#define CEF_VERSION_MINOR 0
#define CEF_VERSION_PATCH 10
#define CEF_COMMIT_NUMBER 3183
#define CEF_COMMIT_HASH "7e14fe138ee5ff3207c9a67539e43af458ce4550"
// clang-format on

#endif // CefVersion
